## Numpy , Pytorch의 Tensor

In [1]:
import numpy as np

In [14]:
n_array = np.arange(10).reshape(2,5)
print(n_array)
print(f"ndim : {n_array.ndim} , shape : {n_array.shape}")

[[0 1 2 3 4]
 [5 6 7 8 9]]
ndim : 2 , shape : (2, 5)


In [5]:
import torch

In [15]:
t_array = torch.FloatTensor(n_array)
print(t_array)
print(f"ndim : {t_array.ndim} , shape : {t_array.shape}")

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])
ndim : 2 , shape : torch.Size([2, 5])


### Tensor 생성은 list , ndarray로 가능하다

In [16]:
data = [[3,5], [10,5]]
x_data = torch.tensor(data)
x_data

tensor([[ 3,  5],
        [10,  5]])

In [17]:
nd_array_ex = np.array(data)
tensor_array = torch.from_numpy(nd_array_ex)
tensor_array

tensor([[ 3,  5],
        [10,  5]], dtype=torch.int32)

In [18]:
data = [[3, 5, 20], [10, 5, 50], [1, 5, 10]]
x_data = torch.tensor(data)

In [19]:
x_data

tensor([[ 3,  5, 20],
        [10,  5, 50],
        [ 1,  5, 10]])

In [32]:
x_data[:] # 0번째 행 부터 마지막 행 까지 출력

tensor([[ 3,  5, 20],
        [10,  5, 50],
        [ 1,  5, 10]])

In [28]:
x_data[1:] # 1 번째 행부터 마지막 행 까지 출력

tensor([[10,  5, 50],
        [ 1,  5, 10]])

In [30]:
x_data[2:] # 2번째 행부터 마지막 행 까지 출력 

tensor([[ 1,  5, 10]])

In [33]:
x_data[:1] # 0 번째 행 만 출력 

tensor([[ 3,  5, 20]])

In [34]:
x_data[:2] # 0 ~ 1번째 행 출력 

tensor([[ 3,  5, 20],
        [10,  5, 50]])

In [35]:
x_data[:3] # 0 ~ 2 번째 행 출력 

tensor([[ 3,  5, 20],
        [10,  5, 50],
        [ 1,  5, 10]])

In [37]:
x_data[:, 1:] # 모든 행에서 1번째 ~ 마지막 열까지 출력 

tensor([[ 5, 20],
        [ 5, 50],
        [ 5, 10]])

In [38]:
x_data[:2, 1:] # 0~1번째 행의 1번째 ~ 마지막 열까지 출력 

tensor([[ 5, 20],
        [ 5, 50]])

In [39]:
x_data.flatten()

tensor([ 3,  5, 20, 10,  5, 50,  1,  5, 10])

In [44]:
torch.ones_like(x_data) # 행렬의 형태 확인 

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [41]:
x_data.numpy()

array([[ 3,  5, 20],
       [10,  5, 50],
       [ 1,  5, 10]], dtype=int64)

In [42]:
x_data.shape

torch.Size([3, 3])

In [43]:
x_data.dtype

torch.int64

### Pytorch의 tensor는 GPU에 올려서 사용가능

In [45]:
x_data.device

device(type='cpu')

In [46]:
if torch.cuda.is_available():
    x_data_cuda = x_data.to('cuda')
x_data_cuda.device

NameError: name 'x_data_cuda' is not defined

In [53]:
tensor_ex = torch.rand(size=(2,3,2))
tensor_ex # element 개수는 12개 (2 x 3 x 2)

tensor([[[0.8906, 0.5495],
         [0.2107, 0.1233],
         [0.3261, 0.4211]],

        [[0.7163, 0.1454],
         [0.1118, 0.7216],
         [0.6625, 0.6806]]])

In [48]:
tensor_ex.shape

torch.Size([2, 3, 2])

In [54]:
tensor_ex.view([-1,6]) # element 개수 12개에 맞추어서 shape을 변경해줌 

tensor([[0.8906, 0.5495, 0.2107, 0.1233, 0.3261, 0.4211],
        [0.7163, 0.1454, 0.1118, 0.7216, 0.6625, 0.6806]])

In [51]:
tensor_ex.view([-1,6]).shape

torch.Size([2, 6])

In [52]:
tensor_ex.reshape([-1,6])

tensor([[0.2382, 0.0983, 0.1381, 0.4602, 0.5415, 0.5890],
        [0.0847, 0.3694, 0.7105, 0.2445, 0.9136, 0.7489]])

In [55]:
a = torch.zeros(3,2)
b = a.view(2,3)

In [56]:
a.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [60]:
b = a.t().reshape(6)
a.fill_(1) # 1로 채우기 

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [62]:
a.t()

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [61]:
b

tensor([1., 1., 1., 1., 1., 1.])

### squeeze() -> 차원 축소, unsequeeze() -> 차원 증가 

In [69]:
tensor_ex = torch.rand(size=(2,1,2))
tensor_ex.squeeze() 

tensor([[0.4662, 0.0027],
        [0.9936, 0.0172]])

In [71]:
tensor_ex.squeeze().shape

torch.Size([2, 2])

In [75]:
tensor_ex = torch.rand(size=(2,2))
tensor_ex.unsqueeze(0).shape # 0번째 자리에 차원 증가?

torch.Size([1, 2, 2])

In [76]:
tensor_ex.unsqueeze(1).shape # 1번째 자리에 차원 증가?

torch.Size([2, 1, 2])

In [79]:
tensor_ex.unsqueeze(2).shape # 2번째 자리에 차원 증가?

torch.Size([2, 2, 1])

## Tensor operations

In [80]:
n1 = np.arange(10).reshape(2,5)
n2 = np.arange(10).reshape(5,2)

In [81]:
t1 = torch.FloatTensor(n1)
t2 = torch.FloatTensor(n2)


In [86]:
n1 # numpy array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [87]:
t1 # torch tensor

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])

In [88]:
t1 + t1

tensor([[ 0.,  2.,  4.,  6.,  8.],
        [10., 12., 14., 16., 18.]])

In [91]:
t1 - t1

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [92]:
t1 + 10

tensor([[10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])

In [94]:
t1 + t2 # 더하는 것들의 차원이 맞아야 덧셈 연산 가능 

RuntimeError: The size of tensor a (5) must match the size of tensor b (2) at non-singleton dimension 1

### 행렬곱 연산의 함수를 dot이 아닌 mm이용
#### dot은 벡터 내적시에 사용, mm은 행렬곱 연산시에 사용

In [95]:
n2 = np.arange(10).reshape(5,2)
t2 = torch.FloatTensor(n2)

In [97]:
t1.shape

torch.Size([2, 5])

In [99]:
t2.shape

torch.Size([5, 2])

In [98]:
t1.mm(t2)

tensor([[ 60.,  70.],
        [160., 195.]])

In [100]:
t1.matmul(t2)

tensor([[ 60.,  70.],
        [160., 195.]])

### matmul()은 브로드캐스팅 연산 됨 , mm은 x

In [104]:
a = torch.rand(5,2,3)
b = torch.rand(3)
a.mm(b) # 브로드캐스팅 연산 불가

RuntimeError: self must be a matrix

In [105]:
a = torch.rand(5,2,3)
b = torch.rand(3)
a.matmul(b)

tensor([[0.7808, 0.9275],
        [0.6041, 0.2667],
        [0.9869, 0.5065],
        [1.0336, 0.8655],
        [0.8043, 0.8018]])

In [117]:
a.matmul(b).shape

torch.Size([5, 2])

In [115]:
a[0].shape

torch.Size([2, 3])

In [114]:
torch.unsqueeze(b,1).shape

torch.Size([3, 1])

In [120]:
# matmul의 브로드 캐스팅 연산 
a[0].mm(torch.unsqueeze(b,1))
a[1].mm(torch.unsqueeze(b,1))
a[2].mm(torch.unsqueeze(b,1))
a[3].mm(torch.unsqueeze(b,1))
a[4].mm(torch.unsqueeze(b,1)).shape

torch.Size([2, 1])

In [121]:
import torch.nn.functional as F

In [122]:
tensor = torch.FloatTensor([0.5, 0.7, 0.1])
h_tensor = F.softmax(tensor, dim = 0)
h_tensor 

tensor([0.3458, 0.4224, 0.2318])

In [125]:
y = torch.randint(5, (10,5))
y

tensor([[2, 4, 1, 1, 4],
        [4, 0, 3, 1, 3],
        [4, 4, 2, 1, 4],
        [0, 1, 4, 2, 3],
        [1, 4, 1, 1, 4],
        [0, 2, 0, 0, 0],
        [1, 3, 1, 3, 4],
        [1, 3, 4, 0, 0],
        [2, 4, 1, 2, 1],
        [2, 0, 2, 3, 1]])

In [129]:
y_label = y.argmax(dim=1)
y_label # 각 행에서 가장 큰 값을 가진 인덱스를 리턴

tensor([1, 0, 0, 2, 1, 1, 4, 2, 1, 3])

In [ ]:
torch.nn.functional.one_hot(y_label)

tensor([[0, 1, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0]])

### 모든 경우의 수를 계산

In [131]:
import itertools
a = [1,2,3]
b = [4,5]
list(itertools.product(a,b))

[(1, 4), (1, 5), (2, 4), (2, 5), (3, 4), (3, 5)]

In [132]:
tensor_a = torch.tensor(a)
tensor_b = torch.tensor(b)
torch.cartesian_prod(tensor_a,tensor_b)

tensor([[1, 4],
        [1, 5],
        [2, 4],
        [2, 5],
        [3, 4],
        [3, 5]])

### AutoGrad

In [136]:
w = torch.tensor(2.0, requires_grad = True)
y = w ** 2
z = 10 * y + 25
z.backward()
w.grad

tensor(40.)

In [141]:
a = torch.tensor([2.,3.], requires_grad=True)
b = torch.tensor([6.,4.], requires_grad=True)
Q = 3*a**3 - b**2
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)


a.grad

tensor([36., 81.])

In [142]:
b.grad

tensor([-12.,  -8.])