In [1]:
import torch

In [ ]:
## https://github.com/rasbt/stat453-deep-learning-ss21/blob/main/L08/code/cross-entropy-pytorch.ipynb

### One-Hot Encoding

In [6]:
y = torch.tensor([0,1,2,1])
num_classes = 3

y_onehot = torch.zeros(y.size(0), num_classes)

print(y_onehot.shape)
print(y_onehot)



torch.Size([4, 3])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [18]:
y_onehot.scatter_(1, y.view(-1, 1).long(), 1).float()

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.]])

### Softmax

In [19]:
#logit

Z = torch.tensor( [[-0.3,  -0.5, -0.5],
                   [-0.4,  -0.1, -0.5],
                   [-0.3,  -0.94, -0.5],
                   [-0.99, -0.88, -0.5]])

Z

tensor([[-0.3000, -0.5000, -0.5000],
        [-0.4000, -0.1000, -0.5000],
        [-0.3000, -0.9400, -0.5000],
        [-0.9900, -0.8800, -0.5000]])

In [20]:
Z.shape

torch.Size([4, 3])

In [22]:
Z[0]

tensor([-0.3000, -0.5000, -0.5000])

In [24]:
Z[0].dim()

1

In [33]:
def softmax(z):
    
    return (torch.exp(z.t()) / torch.sum(torch.exp(z), dim=1)).t()

softmax1 = softmax(Z)
softmax1

tensor([[0.3792, 0.3104, 0.3104],
        [0.3072, 0.4147, 0.2780],
        [0.4263, 0.2248, 0.3490],
        [0.2668, 0.2978, 0.4354]])

In [34]:
def cross_entropy(softmax, y_target):
    print(torch.log(softmax) * (y_target))
    return - torch.sum(torch.log(softmax) * (y_target), dim=1)

In [35]:
xent = cross_entropy(softmax1, y_onehot)
print('Cross Entropy:', xent)

tensor([[-0.9698, -0.0000, -0.0000],
        [-0.0000, -0.8801, -0.0000],
        [-0.0000, -0.0000, -1.0527],
        [-0.0000, -1.2114, -0.0000]])
Cross Entropy: tensor([0.9698, 0.8801, 1.0527, 1.2114])
